# Generated by Django 4.0.4 on 2022-06-27 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Placed', max_length=100)),
                ('productname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.products')),
            ],
        ),
    ]
